# Generated by Django 3.2.5 on 2021-08-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdimeeting',
            old_name='carrer_goal',
            new_name='career_goal',
        ),
        migrations.RemoveField(
            model_name='pdimeeting',
            name='carrer_tier_goal',
        ),
        migrations.AddField(
            model_name='pdimeeting',
            name='career_tier_goal',
            field=models.SmallIntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3'), (4, 'Nível 4')], default=1),
        ),
        migrations.AlterField(
            model_name='pdiplan',
            name='plan_type',
            field=models.SmallIntegerField(choices=[(1, 'Desenvolver'), (2, 'Aprimorar'), (3, 'Reduzir')], default=1),
        ),
    ]
