# Generated by Django 3.2.5 on 2021-08-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210804_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='description',
            field=models.CharField(help_text='Descreva o plano de ação', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdiplan',
            name='description',
            field=models.CharField(help_text='Descrição / Objetivo do Plano', max_length=120),
        ),
    ]
