# Generated by Django 3.2.5 on 2021-08-18 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210720_0014'),
        ('core', '0003_auto_20210816_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.SmallIntegerField(choices=[(1, '&#128557'), (2, '&#128552'), (3, '&#128560'), (4, '&#128551'), (5, '&#128543'), (6, '&#128542'), (7, '&#128533'), (8, '&#128524'), (9, '&#128521'), (10, '&#128540'), (11, '&#1F642'), (12, '&#129321')])),
                ('score', models.SmallIntegerField()),
                ('commentary', models.TextField(max_length=300, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('one_on_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_on_one', to='core.oneononemeeting')),
                ('pdi_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdi_meeting', to='core.pdimeeting')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.userprofile')),
            ],
        ),
    ]
