# Generated by Django 3.2.5 on 2021-08-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meetingevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingevaluation',
            name='feeling',
            field=models.SmallIntegerField(),
        ),
    ]
