# Generated by Django 3.2.5 on 2021-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_meetingevaluation_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneononemeeting',
            name='subject_five',
            field=models.CharField(help_text='Insira um tópico da reunião', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oneononemeeting',
            name='subject_four',
            field=models.CharField(help_text='Insira um tópico da reunião', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oneononemeeting',
            name='subject_three',
            field=models.CharField(help_text='Insira um tópico da reunião', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oneononemeeting',
            name='subject_two',
            field=models.CharField(help_text='Insira um tópico da reunião', max_length=255, null=True),
        ),
    ]
