# Generated by Django 3.2.5 on 2021-08-20 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210820_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdimeeting',
            name='next_meeting',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 1, 21, 2, 865084)),
        ),
    ]
