# Generated by Django 3.2.5 on 2021-07-20 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.occupation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.SmallIntegerField(choices=[(1, 'Colaborador'), (2, 'Líder')], default=1),
        ),
    ]
