# Generated by Django 3.2.5 on 2021-08-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210720_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leader_id',
            field=models.IntegerField(default=2),
        ),
    ]
